### ISSUE TITLE
dirty records in characters_metadata

### ISSUE THREAD

**Issue by dornheimer** [dornheimer/moviedialogs_db#2]
example:
`u5784 +++$+++ WENDY                                              ] +++$+++ m382 +++$+++ happy campers +++$+++ ? +++$+++ ?`

it doesn't show here, but the name field is 52 characters long and record is missing info for gender and credit position.

the record is actually a *duplicate* of the previous record in the file:
`u5783 +++$+++ WENDY +++$+++ m382 +++$+++ happy campers +++$+++ f +++$+++ 2`

i have found two similar cases so far. what is the best way to handle this? changing, i.e. removing a character implies changing all references to it in the other tables. so, remove `u5784` and update all its references to link to `u5783`?

**Comment by fspoettel** [comment]
Are these all simple mistakes in the data? In that case, removing references would be a good solution. We could also map the correct information from `u5783` to `u5784` during import while keeping the references across the db intact.

**Comment by dornheimer** [comment]
from what i can tell, these duplicates only exist because of some formatting issue in the name field. duplicates only have very little data associated with them and their real ids already contain all of it.
characters i have found so far:
- u5784 -> u5783
- u5786 -> u5785
- u6564 -> u6563
