### ISSUE TITLE
html tags in lines

### ISSUE THREAD

**Issue by dornheimer** [dornheimer/moviedialogs_db#4]
~~some~~ many lines have underline tags in them:

`L55857 +++$+++ u135 +++$+++ m9 +++$+++ REEF +++$+++ And his 'egghead' son!  We'll give 'em a <u>rough</u> <u>reception</u>, won't we?`

**Comment by dornheimer** [comment]
tags:
- `<u></u>`
- `<i></i>`
- `<b></b>`

**Comment by fspoettel** [comment]
Let's discuss how to handle these when we actually start implementing logic that depends on plaintext.
